FROM registry.cn-beijing.aliyuncs.com/roselle-1/chat:base

WORKDIR /sanic

COPY Bard.py common.py keywords.txt dfa.py send_mail.py logger.py app.py EdgeGPT.py BingImageCreator.py conversation_ctr.py /sanic/
